site_name: aequos Modern Data Visualizer solution for SharePoint Online
site_url: 'http://127.0.0.1:8000/'
use_directory_urls: true
nav:
  - Getting Started:
    - Introduction: index.md
    - Get a license: get_license.md
    - Installation: installation.md
    - Activate a standalone license: setup_standalone.md
    - Connections overview: getting_started/connections_chart.md
    - Features comparison with PnP Modern Search v4: features.md
    - Upgrade from PnP Modern Search v4: upgrade_from_pnp.md
  - Data Visualizer:
    - Usage: usage/data-visualizer/index.md
    - Data sources: usage/data-visualizer/data-sources/index.md
    - Slots: usage/data-visualizer/slots.md
    - Tokens: usage/data-visualizer/tokens.md
    - Adaptive expressions: usage/data-visualizer/adaptive_exressions.md
    - Layouts: usage/data-visualizer/layouts/index.md
    - Connections: usage/data-visualizer/connections/index.md
    - Extensibility: extensibility/index.md
  - Data Filters:
    - Usage: usage/data-filters/index.md
    - Layouts: usage/data-filters/layouts/index.md
  - Data Verticals:
    - Usage: usage/data-verticals/index.md 
  - Search Box:
    - Usage: usage/search-box/index.md
  - Group metadata editor:
    - Usage: usage/group-tag-manager/index.md
  - Extensibility:
    - Introduction: extensibility/index.md
    - Templating: extensibility/templating.md
    - Custom data source: extensibility/custom_data_source.md
    - Custom layout: extensibility/custom_layout.md
    - Custom web component: extensibility/custom_web_component.md
    - Custom suggestions provider: extensibility/custom_suggestions_provider.md
    - Custom Handlebars customizations: extensibility/handlebars_customizations.md
    - Web component list: extensibility/web_components_list.md
  - Tutorials & How-Tos: getting_started/tutorials/index.md
theme:
  name: 'material'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
  font:
    code: 'Ubuntu Mono'
  logo: 'assets/aequos_logo.png'
  icon:
    logo: material/cloud
extra_css:
  - 'assets/extra.css'
markdown_extensions:
  - pymdownx.tabbed          
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde 
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - markdown_include.include:
          base_path: docs
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/aequos_ca'
    - icon: fontawesome/brands/twitter
      link: 'www.aequos.ca'
repo_url: https://github.com/aequos-solutions/aequos.github.io
edit_uri: blob/master/docs